### ISSUE TITLE
Cursor drifts up during gameplay

### ISSUE THREAD

**Issue by jackivan88** [fogleman/Craft#163]
While running on Windows 10 Professional 64-bit the cursor constantly drifts up. When you are looking at the ground it moves quickly, then slows down about 45 degrees under the horizon, and then begins moving rapidly again about 45 degrees above the horizon until you're looking straight up. The cursor stops moving when you press `esc`. [This video demonstrates the issue](https://youtu.be/_e8HM4-Jvy4).

<iframe width="420" height="315" src="https://www.youtube.com/embed/_e8HM4-Jvy4" frameborder="0" allowfullscreen></iframe>

I've attempted running in compatibility mode, and my students using Windows have all been able to reproduce this. Any idea what we can do to correct the problem?

**Comment by fogleman** [comment]
Looks like a GLFW bug that was fixed but the glfw source isn't up to date in my repo.

https://github.com/glfw/glfw/issues/251

You can try patching and rebuilding. Let me know if it works.

**Comment by Fixer-007** [comment]
Any news on this? @jackivan88

**Comment by satoshinm** [comment]
If this still occurs, could try rebuilding with https://github.com/fogleman/Craft/pull/178 - updates to glfw 3.1.2 (https://github.com/glfw/glfw/issues/251 was fixed in glfw 3.0.4+)

**Comment by SeanRamey** [comment]
This still occurs. I have the same issue on Windows 10 Home.
